CREATE TABLE "EXN1"."MERGE_STATE_0"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE0_KEY_IX" ON "EXN1"."MERGE_STATE_0" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE0_1IX" ON "EXN1"."MERGE_STATE_0" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE0_2IX" ON "EXN1"."MERGE_STATE_0" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_1"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE1_KEY_IX" ON "EXN1"."MERGE_STATE_1" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE1_1IX" ON "EXN1"."MERGE_STATE_1" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE1_2IX" ON "EXN1"."MERGE_STATE_1" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_2"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE2_KEY_IX" ON "EXN1"."MERGE_STATE_2" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE2_1IX" ON "EXN1"."MERGE_STATE_2" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE2_2IX" ON "EXN1"."MERGE_STATE_2" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_3"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE3_KEY_IX" ON "EXN1"."MERGE_STATE_3" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE3_1IX" ON "EXN1"."MERGE_STATE_3" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE3_2IX" ON "EXN1"."MERGE_STATE_3" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_4"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE4_KEY_IX" ON "EXN1"."MERGE_STATE_4" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE4_1IX" ON "EXN1"."MERGE_STATE_4" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE4_2IX" ON "EXN1"."MERGE_STATE_4" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_5"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE5_KEY_IX" ON "EXN1"."MERGE_STATE_5" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE5_1IX" ON "EXN1"."MERGE_STATE_5" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE5_2IX" ON "EXN1"."MERGE_STATE_5" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_6"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE6_KEY_IX" ON "EXN1"."MERGE_STATE_6" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE6_1IX" ON "EXN1"."MERGE_STATE_6" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE6_2IX" ON "EXN1"."MERGE_STATE_6" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_7"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE7_KEY_IX" ON "EXN1"."MERGE_STATE_7" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE7_1IX" ON "EXN1"."MERGE_STATE_7" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE7_2IX" ON "EXN1"."MERGE_STATE_7" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_8"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE8_KEY_IX" ON "EXN1"."MERGE_STATE_8" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE8_1IX" ON "EXN1"."MERGE_STATE_8" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE8_2IX" ON "EXN1"."MERGE_STATE_8" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE TABLE "EXN1"."MERGE_STATE_9"
(
    "CALL_TYPE"     VARCHAR2(3),
    "IMSI"          VARCHAR2(15),
    "CALL_NUM"      VARCHAR2(25),
    "CHARGE_TYPE"   VARCHAR2(2),
    "IR_SRC"        VARCHAR2(3),
    "CHARGE"        NUMBER(*,0) NOT NULL,
    "DURATION"      NUMBER(*,0) NOT NULL,
    "VOLUME"        NUMBER(*,0) NOT NULL,
    "START_DTM"     DATE,
    "TIME_KEY"      NUMBER(*,0) NOT NULL
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."MERGE_STATE9_KEY_IX" ON "EXN1"."MERGE_STATE_9" ("CALL_TYPE", "IMSI", "CALL_NUM", "CHARGE_TYPE", "IR_SRC", "CHARGE", "DURATION", "VOLUME", "TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE9_1IX" ON "EXN1"."MERGE_STATE_9" ("IR_SRC") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."MERGE_STATE9_2IX" ON "EXN1"."MERGE_STATE_9" ("TIME_KEY") TABLESPACE "CCARE_FRAUD_ALERT";
